### PR TITLE
Bug on clearing recycle times

### PR DESCRIPTION
**Pull request by oscarcenteno**
Please check that it doesnt work on clearing recycle times with -1.

### CODE REVIEW

**Comment by oscarcenteno** [comment]
Thanks Mike. How can I get access to a new release? I cannot compile the source since it requires a private key for signing your assemblies.

**Comment by mikefourie** [comment]
I'll push out a new release in a day or two. can you wait? you could skip verification for the key if using a private build.

tempted to remove signing all together....

**Comment by oscarcenteno** [comment]
Ok we'll  wait for you.

Msbuild extension pack is installed on the 55 servers where we run our deployment builds.

We use it on every automated release, with more than 150 developers working on our apps.

So… yes we will wait!






From: Mike Fourie
Sent: ‎Wednesday‎, ‎February‎ ‎4‎, ‎2015 ‎4‎:‎25‎ ‎PM
To: mikefourie/MSBuildExtensionPack
Cc: Oscar Centeno





I'll push out a new release in a day or two. can you wait? you could skip verification for the key if using a private build.

tempted to remove signing all together....

**Comment by oscarcenteno** [comment]
Hi Mike,I hope you are doing fine.
Just a quick reminder for the new release :-)
We appreciate your help! Oscar

Date: Wed, 4 Feb 2015 14:25:45 -0800

**Comment by oscarcenteno** [comment]
Hi Mike, I hope you are doing fine!
Do you think we could get a new release of Extension Pack?We are already planning a release of our system and really need the issue we fixed.
Thank you!Oscar.

Date: Wed, 4 Feb 2015 14:25:45 -0800

**Comment by mikefourie** [comment]
eta a few days. sorry for delay...

**Pull request merged**
