### PR TITLE
Add missing NUnit3 task

### PR DESCRIPTION
**Pull request by patrickmaurer**

### CODE REVIEW

**Comment by patrickmaurer** [comment]
Looks like there are other changes done to the NUnit3 task since the last release (4.0.12.0). The currently shipped version is not working at all. Is there already a date set for the next release?

**Comment by mikefourie** [comment]
thanks. will look at getting a refresh out over the next few days

**Comment by patrickmaurer** [comment]
did you find some time to get the release ready and when do you think we will see this release? thanks again.

**Comment by mikefourie** [comment]
sorry! been sidelined. will try get it out in the next few days (repetition not intended!)

**Pull request merged**
